### ISSUE TITLE
extract image alone

### ISSUE THREAD

**Issue by mahmooudali7** [Dynamsoft/Dynamic-Web-TWAIN#13]
Dears ,
i'm using Dynamsoft with angular 5 and when i try to drag pdf file ,the scanner extract images and display it only not the pdf page

this form library documentaion :- When loading in a PDF file, DWT tries to extract images from that file, which is why the SDK can handle image-based PDF documents by default

how i can change it ?

**Comment by Grace-Dynamsoft** [comment]
The root cause is that you do not user pdf rasterizer addon, instead with the image library, it can only extract the image information from your file, that's right. Change the convert mode to render all with code DWObject.Addon.PDF.SetConvertMode(1), then everything would be fine. Ps: you should make sure that your license has pdf rasterizer addon included:)  good luck!

**Comment by rebeccakak** [comment]
If you have any further questions, feel free to contact us via support@dynamsoft.com
