### ISSUE TITLE
Add capability to not show License expiration popup

### ISSUE THREAD

**Issue by July52rus** [Dynamsoft/Dynamic-Web-TWAIN#20]
Hi! Could you please add capability to not show License expiration popup or at least add close icon on it. Because it blocks entire application.

Thank you!

<img width="639" alt="image" src="https://user-images.githubusercontent.com/20466601/156168262-fc645542-c76d-4bbb-9ae9-68374ecc6be7.png">

**Comment by Grace-Dynamsoft** [comment]
Actually it is by design based on current version. Dynamic-Web-Twain make strict license verifications no matter this popup closed or not.  For sure, we will evaluate your concern in the later version.  Any problems for a quick response, please feel free to mail our technical support: support@dynamsoft.com.
