### ISSUE TITLE
How to override install.js when using npm package?

### ISSUE THREAD

**Issue by rooby** [Dynamsoft/Dynamic-Web-TWAIN#5]
I have been using a custom install of the DWT code due to having to override the install.js (as per this documentation: https://developer.dynamsoft.com/dwt/kb/2902).

I would like to switch to use the npm package, however I'm not sure how to handle this install.js modification.
Is there a way it can be done similar to how you can override the config.js?

**Comment by Tom-Dynamsoft** [comment]
@rooby yes. The change is like how you would override config.js

1. In your code, override ResourcesPath to point to your own copy of the Resources which includes install.js (on your server probably)

Dynamsoft.WebTwainEnv.ResourcesPath = "https://tst.dynamsoft.com/libs/dwt/15.0";

2. Change your copy of the install.js

Since DWT loads the install.js from the ResourcesPath, the above change would mean you are able to change your own copy however you'd like to. :)
